### ISSUE TITLE
how to use it on subdomain

### ISSUE THREAD

**Issue by djoudi** [iateadonut/laravel51-cpanel-quick-deploy#1]
how to deploy on subdomain?

**Comment by iateadonut** [comment]
If you have assigned the subdomain in the account name itself, you simply use it as is.

However, if you are using a subdirectory as a subdomain, you don't need this and should use a regular laravel install.  The problem with CPanel (as opposed to Virtualmin) is that the top-level account root directory cannot be defined, so instead of public like in a laravel installation, you need it to be public_html.

So, in the case of a subdomain as created in CPanel:
1) In CPanel, click on subdomains.
2) Define your subdomain, having the document root to /sub/public
3) After that, you just install Laravel 5.1 as normal in /sub , and you have no need for this 'laravel51-cpanel-quick-deploy'.
